/* Link-quality contract shared by the event refresh and regression tests. */
const TRACKING_KEYS = /^(?:utm_[^=]+|fbclid|gclid|mc_[^=]+)$/i;
const API_PATH = /(?:^|\/)(?:api|v\d+|rss|feed|feeds|search)(?:\/|$)|\.json(?:$|\?)/i;
export function sourceIdFor(source = {}) { return String(source.id || source.sourceId || source.name || 'unknown').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '') || 'unknown'; }
export function normalizeOfficialUrl(value) { try { const url = new URL(value); if (!/^https?:$/.test(url.protocol)) return ''; url.protocol = 'https:'; url.hash = ''; [...url.searchParams.keys()].forEach(key => { if (TRACKING_KEYS.test(key)) url.searchParams.delete(key); }); return url.href; } catch { return ''; } }
export function allowedHostsFor(source = {}) { return [...new Set([source.domain, ...(source.linkHosts || [])].map(host => String(host || '').toLowerCase()).filter(Boolean))]; }
export function isAllowedOfficialUrl(value, source = {}) { try { const hostname = new URL(value).hostname.toLowerCase(); return allowedHostsFor(source).some(host => hostname === host || hostname.endsWith('.' + host)); } catch { return false; } }
export function isUserFacingUrl(value) { try { const url = new URL(value); return /^https?:$/.test(url.protocol) && !API_PATH.test(url.pathname); } catch { return false; } }
export function landingUrlFor(source = {}) { const landing = normalizeOfficialUrl(source.landingUrl || ''); return landing && isAllowedOfficialUrl(landing, source) && isUserFacingUrl(landing) ? landing : ''; }
export function staticLinkResult(event, source) { const canonicalUrl = normalizeOfficialUrl(event.canonicalUrl || event.url || ''); const fallbackUrl = normalizeOfficialUrl(event.fallbackUrl || landingUrlFor(source)); if (!canonicalUrl || !isAllowedOfficialUrl(canonicalUrl, source) || !isUserFacingUrl(canonicalUrl)) return { canonicalUrl, fallbackUrl, linkStatus: 'invalid', linkCheckMethod: 'static', linkEvidence: 'URL is missing, off allowlist, or is an API/feed/search endpoint.' }; return { canonicalUrl, fallbackUrl, linkStatus: 'unknown', linkCheckMethod: 'static', linkEvidence: 'Static URL policy passed.' }; }
export function titleMatchesPage(title, html) { const words = String(title || '').toLowerCase().match(/[a-z0-9]{4,}/g) || []; if (!words.length) return true; const page = String(html || '').toLowerCase(); return words.filter(word => page.includes(word)).length >= Math.min(2, words.length); }
export async function checkLink(event, source, { fetchImpl = fetch, timeoutMs = 12000 } = {}) { const result = staticLinkResult(event, source); const checkedAt = new Date().toISOString(); if (result.linkStatus === 'invalid') return { ...result, linkCheckedAt: checkedAt }; try { const response = await fetchImpl(result.canonicalUrl, { headers: { 'user-agent': 'SouthBayFamilyFindsLinkHealth/1.0' }, redirect: 'follow', signal: AbortSignal.timeout(timeoutMs) }); const redirectTarget = normalizeOfficialUrl(response.url || result.canonicalUrl); const html = await response.text(); if (response.status === 403) return { ...result, linkStatus: 'blocked-machine', linkCheckMethod: 'machine', linkCheckedAt: checkedAt, redirectTarget, linkEvidence: 'GET returned 403; user-browser availability is not inferred.' }; if (response.status === 404 || response.status === 410) return { ...result, linkStatus: 'not-found', linkCheckMethod: 'machine', linkCheckedAt: checkedAt, redirectTarget, linkEvidence: 'GET returned ' + response.status + '.' }; if (!response.ok) return { ...result, linkStatus: 'unknown', linkCheckMethod: 'machine', linkCheckedAt: checkedAt, redirectTarget, linkEvidence: 'GET returned ' + response.status + '.' }; if (!isAllowedOfficialUrl(redirectTarget, source)) return { ...result, linkStatus: 'unknown', linkCheckMethod: 'machine', linkCheckedAt: checkedAt, redirectTarget, linkEvidence: 'Redirect left the official source allowlist.' }; if (!titleMatchesPage(event.title, html)) return { ...result, linkStatus: 'content-mismatch', linkCheckMethod: 'machine', linkCheckedAt: checkedAt, redirectTarget, linkEvidence: 'Page did not contain enough title identity signals.' }; return { ...result, canonicalUrl: redirectTarget, linkStatus: redirectTarget === result.canonicalUrl ? 'ok' : 'redirected', linkCheckMethod: 'machine', linkCheckedAt: checkedAt, redirectTarget, linkEvidence: 'GET succeeded and title identity matched.' }; } catch (error) { return { ...result, linkStatus: 'unknown', linkCheckMethod: 'machine', linkCheckedAt: checkedAt, linkEvidence: 'GET failed: ' + String(error.message || error).slice(0, 160) }; } }
export function resolvePublishedLink(event, result) { const canonicalWorks = ['ok', 'redirected', 'blocked-machine'].includes(result.linkStatus); const url = canonicalWorks ? result.canonicalUrl : result.fallbackUrl; return { ...event, sourceId: event.sourceId || sourceIdFor({ name: event.source }), canonicalUrl: result.canonicalUrl || '', sourceLandingUrl: result.fallbackUrl || '', fallbackUrl: result.fallbackUrl || '', linkStatus: result.linkStatus, linkCheckedAt: result.linkCheckedAt, linkCheckMethod: result.linkCheckMethod, redirectTarget: result.redirectTarget || '', linkEvidence: result.linkEvidence, linkResolution: canonicalWorks ? 'canonical' : (url ? 'fallback' : 'unavailable'), url: url || '' }; }
export async function auditLinks(events, sources, options = {}) { const sourceByName = new Map(sources.map(source => [source.name, source])); const concurrency = Math.max(1, Math.min(Number(options.concurrency) || 6, 12)); const output = new Array(events.length); let cursor = 0; await Promise.all(Array.from({ length: concurrency }, async () => { while (cursor < events.length) { const index = cursor++; const event = events[index]; const source = sourceByName.get(event.source) || { name: event.source, domain: '' }; const result = await checkLink(event, source, options); output[index] = resolvePublishedLink({ ...event, sourceId: event.sourceId || sourceIdFor(source) }, result); } })); const counts = output.reduce((all, event) => { all[event.linkStatus] = (all[event.linkStatus] || 0) + 1; return all; }, {}); return { events: output, counts }; }
